- README.md
- esawsfunctions/funk.py
Update required for refactoring aggregation.
> Mc updae get sqs

- README.md
- esawsfunctions/funk.py
- Implementing write_dataframe_to_csv
> Implementing save csv

- .gitignore
- esawsfunctions/funk.py
- Added two functions:
- movement_calculation_a
- movement_calculation_b
- Both functions take current value of two iterable lists and performs equation, returning the result
- Updated .gitignore to include .vscode
> Added movement calculations for imputation

- README.md
- es_aws_functions/aws_functions.py
- es_aws_functions/exception_classes.py
Adds in a get_sqs_messages function and moves the donthavealldataerror into aws funcs
> get_sqs_messages function

- dev-requirements.txt
- docker-compose.yml
- ec2_describe.sh
- serverless.yml
- yaml_lint_config.yml
* added a yammlint config file
* added a ec2 describe sh file
* added yammlint to dev requirements
* linted all yaml files in repo
Note that due to the chicken and egg problem this PR doesn’t have an automatic yamllint errors, but it’s been tested to work in the ‘mock’ concourse environment
> Lu4987 yamllint

- GeneralFunctions.md
- es_aws_functions/general_functions.py
Sas doesnt do the nearest even type of rounding that the python round() function does.
> added sas_round function to gen funk

- es_aws_functions/aws_functions.py
- es_aws_functions/general_functions.py
I added a couple of extra bits. The bucket/key in err message as Kris suggested, and the outer line number as well as the inner(i noticed with a boto error, the line number was somewhere in botocore stuff)
> Error handling update

- es_aws_functions/general_functions.py
- es_aws_functions/test_generic_library.py
Changes i realised would be needed once i started adding this into enrichment
> minor changes for generic error handling

- es_aws_functions/test_generic_library.py
When updating the Disclosure Tests to use the Generic Test Library, it was discovered that the methods don't have environment variables. As such the default behaviour of setting them up failed as the modules didn't import os. As such I added a simple if statement and we now expect any code that doesn't have environment variables to sent in False so that it doesn't try setting them up.
> WIP - Amended for functions that don't have Environment Variables.

- es_aws_functions/aws_functions.py
Added Exception type to the error message so that ClientError tests can still work when dealing with read_from_s3
> Add exception type to read_from_s3 exception

- GeneralFunctions.md
- TestGenericLibrary.md
- es_aws_functions/general_functions.py
- es_aws_functions/test_generic_library.py
Added a new function for testing.
Also resolved this issue: https://github.com/ONSdigital/es-functions/issues/53
> Replacement invoke

- es_aws_functions/aws_functions.py
Added current stage as a hard-coded variable in the module.
Added total steps as value in the config.
- To be added to the status message as per the contract.
> Minor change to the method stage  params to be used in the status msg

- es_aws_functions/aws_functions.py
- es_aws_functions/general_functions.py
Changed the import for send_bpm_message in general_functions
> Spp 33 lg add status msg error

- documentation/AWSFunctions.md
- documentation/TestGenericLibrary.md
- es_aws_functions/aws_functions.py
- es_aws_functions/test_generic_library.py
Added Faked SQS Queue So Tests Don't Try To Use Real. Unsure Why BMI Tests Work Without Mocked SQS?
Tidied Up Docs As They Were Missing A Function. Added My New One As Well.
> Mocked Queue

- es_aws_functions/aws_functions.py
Added dumps for the queue message as this is needed.
Added conversion of run_id to string incase it is passed as float
> Dumps is needed whoops

- dev-requirements.txt
Added immutables and upgraded pyptz
> Added logger required dependencies.

- es_aws_functions/general_functions.py
Spp-Logger no longer needs user in the config so have removed it.
> Removed user from the setup of logger as no longer expected

- es_aws_functions/general_functions.py
Luke never had this PR'd passing over to the guys to check we still want this change.
> Changed status message for a more meaningful one for the user.

- layer-requirements.txt
> Pinned logger

- es_aws_functions/general_functions.py
Status must be one of IN PROGRESS, DONE, ERROR
> Spp 1279 default total steps zero + Status enum
